markdown: kramdown
kramdown:
  input: GFM

exclude:
  - "bin/"
  - "Gemfile"
  - "Gemfile.lock"

url: http://nicbenders.com
future: true

plugins:
  - jekyll-feed

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "bin"
  - "README.md"
